apiVersion: v1
kind: Secret
metadata:
  name: "transtats-secret"
  labels:
    app: "transtats"
stringData:
  django-secret-key: "SomeSecretKey"
  database-password: "postgres"
  oidc-client-secret: ""
  database-host: db.stg.tshost.com
  database-user: postgres
